### ISSUE TITLE
Questions on `array.rs`

### ISSUE THREAD

**Issue by fuyufjh** [skyzh/type-exercise-in-rust#5]
https://github.com/skyzh/type-exercise-in-rust/blob/db610776e6190b067560baa4efe65d7078098b64/archive/day2/src/array.rs#L20-L39

Q1: Could this be better? ~~It's a tighter constraint, I think.~~ Seems no difference

```diff
 /// [`Array`] is a collection of data of the same type. 
 pub trait Array: Send + Sync + Sized + 'static 
-where 
-    for<'a> Self::OwnedItem: Scalar<RefType<'a> = Self::RefItem<'a>>, 
 { 
     /// The corresponding [`ArrayBuilder`] of this [`Array`]. 
     /// 
     /// We constriant the associated type so that `Self::Builder::Array = Self`. 
     type Builder: ArrayBuilder<Array = Self>; 
  
     /// The owned item of this array. 
-    type OwnedItem: Scalar<ArrayType = Self>; 
+    type OwnedItem: for<'a> Scalar<ArrayType = Self, RefType<'a> = Self::RefItem<'a>>;
```

Q2: What's the purpose of

```rust
     where 
         Self: 'a; 
```

in line 37-38? Can we remove that?

**Comment by skyzh** [comment]
> Q1: Could this be better? It's a tighter constraint, I think. Seems no difference

Yes, that's the same.

> in line 37-38? Can we remove that?

Yes, as we have `'static` bound on `Array`, we don't need this.

To explain this in detail, let's take a look at the signature of `get`:

```rust
fn get(&self, idx: usize) -> Self::RefItem<'_>;
```

The lifetime of `RefItem<'_>` must be as long as `&self`. If we do not have `'static` bound on `Array`, this constraint might be violated. Therefore, if `Array` is not `'static`, we can add `Self: 'a` bound on `RefItem`, so as to make everything looks reasonable.

I once thought of implementing `Array` on `&PrimitiveArray` instead of the owned type, but gave up. If we go along that way, the `Self: 'a` bound should be added.
